### PR TITLE
Refactoring all the feature files into separate folder

### PR DESCRIPTION
**Pull request by sherrif10**
Refactoring all the feature files into separate folder to have a clear track of each scenario with its corresponding step definitions. This work is based on the work that is supposed to be accomplised, so we can use it as a start cc @mozzy11   @moshonk

### CODE REVIEW

**Comment by mozzy11** [comment]
@sherrif10 , i think this is not right.
we should have a single feature file for a single test case , and then we have the different use cases expresses as a scenario inside a feature.

we should not have feature files for all the use cases.

example we should have a single feature file for   Test case 3  : Adding a Patient   
and then have use cases expressed as Scenarios inside that file ie  3.1 : Adding an Adult Patient  ,3.2: Adding a Pediatric Patient

**Comment by sherrif10** [comment]
> example we should have a single feature file for Test case 3 : Adding a Patient
> and then have use cases expressed as Scenarios inside that file ie 3.1 : Adding an Adult Patient ,3.2: Adding a Pediatric Patient

Thanks @mozzy11 , i  agree with you on this, having scenarios into one single test. However still we need these other folders separately. is there any other folder that can me improved.

**Comment by sherrif10** [comment]
> * Scenario :Adding an Adult Patient
> * Scenario: Adding a Pediatric Patient

It first represented as if these are two different cases but with minor change. We can have this in one step defintion class.Thanks, will update this.

**Comment by sherrif10** [comment]
Hello @mozzy11  @moshonk , hope this is ready for merge.

**Pull request closed without merging**
