### PR TITLE
Test Case 7 : Check Complete list of forms

### PR DESCRIPTION
**Pull request by sherrif10**
https://github.com/IsantePlus/isanteplus-qaframework/issues/17

### CODE REVIEW

**Comment by sherrif10** [comment]
Hello @mozzy11  Hope this is ready to be merged

**Comment by mozzy11** [comment]
@sherrif10 can you resolve the merge conflicts

**Comment by sherrif10** [comment]
cc @mozzy11

**Comment by mozzy11** [comment]
Thanks @sherrif10 ,
LGTM

**Pull request merged**
